---
kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine:3.8
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
  - echo ${USERNAME}
  - echo ${PASSWORD}

---
kind: secret
name: username
get:
  path: secret/data/docker
  name: username

---
kind: secret
name: password
get:
  path: secret/data/docker
  name: password
