---
kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine:3.8
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
  - env
---
kind: secret
name: username
get:
  path: secret/data/docker
  name: username
