kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - echo "hi there"
  - echo ${USERNAME}

---
kind: secret
name: test

external_data:
  username:
    path: kv/docker
    name: username
