---
kind: pipeline
type: docker
name: greeting

steps:
- name: env
  image: ubuntu:jammy
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
  - echo "the username is $${USERNAME}"
  - echo "and the password is $${PASSWORD}"
  - cat send_mail.sh
  - apt update && apt install -y curl
  - curl --version
  - chmod +x send_mail.sh
  - stat send_mail.sh
  - bash send_mail.sh
  - cat curl_output.txt

---
kind: secret
name: username
get:
  path: secret/data/docker
  name: username

---
kind: secret
name: password
get:
  path: secret/data/docker
  name: password
