---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine

---
kind: secret
name: username
get:
  path: secret/docker
  name: username

---
kind: secret
name: password
get:
  path: secret/docker
  name: password
